apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: r1v8zkhrf-go-gitops
  description: This is GitOps manifest for r1v8zkhrf-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: r1v8zkhrf-go
    backstage.io/kubernetes-id: r1v8zkhrf-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:r1v8zkhrf-go
